# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
