# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.Subject'),
            preserve_default=False,
        ),
    ]
