# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20160507_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
